language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: mxu+e+KyZjhBKUwNSLktKjQOPqIOd1Enr0YkG1MpKTyh7rI7wBR8h0IpUO7k4VK4N59JTbxAv1ANv0s2/CHm6q7Y6GPsL8+V/xEd9iBhQnMK7iZIkNaW3jQcdrZ3B333BvmdjbWr5AVnnpg2gX+JMFyVCf7rfJ7Kv6bZMm0BpLBdKodztTrdhfDzRxyv/KmNYApx5GSEy01lNWYUqdCPjxyq1+2VdBD97HbhIR/xRipvf1uGiogH5jgxM0reFnWo3WJCWyAPwoNo5kAKrOvSvNBL5213Ux3yPv0FmOnXtRIjPDMTnPzAT7fe8XkhwE8Rd8+HNfzB7yqFBB8qlaWj5abmf3BmpOVPhsGf/5JYnU2POfEt+1ol+QvviYENigh2xxGCxpEPmB19fkaVHqZxhrzJ4z7z8VpldqYSIVsIHbWTdQoGWRIZ3VEe/NA2X5GqEjhmvKOrWTLk8mFjrJv2hVHoQnaNkuOtPq8ugRk+5jwhMLqy2za7IVi0vnjF7PNN7/vGZ+16X+EjbFTSlVSJCw3vc+zmXYlrJCQgfglKshkSppmG471N4ytuDYDF6vldTBz/P9lxWxktTn03r+8MJfq3BxXLd5CKOnxEYJxWH8PBSOnWdaYl8+fYfanp8Klw/UxzG8erQF1kwn5IJS1DcAVe3JITAXLEj9+2SOczpWE=
  file:
    - 'remark-unlink.js'
    - 'remark-unlink.min.js'
  on:
    tags: true
